spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
server.servlet.session.cookie.secure=true
app.registration-enabled=${REGISTRATION_ENABLED:false}
