package dev.hexora.security;
import dev.hexora.dto.response.ApiResponse; import dev.hexora.enums.RoleType; import dev.hexora.model.*; import dev.hexora.repository.*; import jakarta.servlet.http.HttpServletRequest; import jakarta.servlet.http.HttpServletResponse; import jakarta.servlet.http.HttpSession; import jakarta.validation.Valid; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.security.authentication.*; import org.springframework.security.core.Authentication; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/auth")
public class AuthController {
 private final AuthenticationManager manager; private final UserRepository users; private final RoleRepository roles; private final PasswordEncoder encoder; private final boolean registrationEnabled;
 public AuthController(AuthenticationManager manager,UserRepository users,RoleRepository roles,PasswordEncoder encoder,@Value("${app.registration-enabled:true}")boolean registrationEnabled){this.manager=manager;this.users=users;this.roles=roles;this.encoder=encoder;this.registrationEnabled=registrationEnabled;}
 @PostMapping("/register") ResponseEntity<?> register(@Valid @RequestBody RegisterRequest r){if(!registrationEnabled)return ResponseEntity.status(403).body(ApiResponse.forbidden("Registration is disabled"));String u=r.username().trim(),e=r.email().trim().toLowerCase();if(users.existsByUsernameIgnoreCase(u)||users.existsByEmailIgnoreCase(e))return ResponseEntity.status(409).body(ApiResponse.error("Username or email is already in use",409));Role role=roles.findByName(RoleType.USER).orElseThrow();User user=new User();user.setUsername(u);user.setEmail(e);user.setPassword(encoder.encode(r.password()));user.setRoles(Set.of(role));users.save(user);return ResponseEntity.status(201).body(ApiResponse.created("User registered successfully",null));}
 @PostMapping("/login") ApiResponse<Map<String,Object>> login(@Valid @RequestBody LoginRequest r,HttpServletRequest req){Authentication a=manager.authenticate(new UsernamePasswordAuthenticationToken(r.usernameOrEmail().trim(),r.password()));SecurityContextHolder.getContext().setAuthentication(a);req.getSession(true);User u=users.findByUsernameIgnoreCase(a.getName()).orElseThrow();Map<String,Object>d=new LinkedHashMap<>();d.put("id",u.getId());d.put("username",u.getUsername());d.put("email",u.getEmail());d.put("roles",u.getRoles().stream().map(x->x.getName().name()).toList());return ApiResponse.success("Login successful",d);}
 @PostMapping("/change-password") ResponseEntity<?> change(@RequestBody Map<String,String> body){Authentication a=SecurityContextHolder.getContext().getAuthentication();if(a==null||!a.isAuthenticated())return ResponseEntity.status(401).body(ApiResponse.unauthorized("Authentication required"));User u=users.findByUsernameIgnoreCase(a.getName()).orElseThrow();if(!encoder.matches(body.get("currentPassword"),u.getPassword()))return ResponseEntity.badRequest().body(ApiResponse.error("Current password is incorrect"));String next=body.get("newPassword");if(next==null||next.length()<8)return ResponseEntity.badRequest().body(ApiResponse.error("New password must contain at least 8 characters"));u.setPassword(encoder.encode(next));users.save(u);return ResponseEntity.ok(ApiResponse.success("Password changed successfully",null));}
}
